const LOGIN_START = 'LOGIN_START';
const LOGIN_SUCCESS = 'LOGIN_SUCCESS';
const LOGIN_FAILED = 'LOGIN_FAILED';
const GET_LINKS_START = 'GET_LINKS_START';
const GET_LINKS_SUCCESS = 'GET_LINKS_SUCCESS';
const GET_LINKS_FAILED = 'GET_LINKS_FAILED';
const CREATE_LINKS_START = 'CREATE_LINKS_START';
const CREATE_LINKS_SUCCESS = 'CREATE_LINKS_SUCCESS';
const CREATE_LINKS_FAILED = 'CREATE_LINKS_FAILED';
// const CREATE_BRANDS_START = 'CREATE_BRANDS_START';
// const CREATE_BRANDS_SUCCESS = 'CREATE_BRANDS_SUCCESS';
// const CREATE_BRANDS_FAILED = 'CREATE_BRANDS_FAILED';
const GET_BRANDS_START = 'GET_BRANDS_START';
const GET_BRANDS_SUCCESS = 'GET_BRANDS_SUCCESS';
const GET_BRANDS_FAILED = 'GET_BRANDS_FAILED';
const GET_SINGLE_PRODUCT_BEGIN = 'GET_SINGLE_PRODUCT_BEGIN';
const GET_SINGLE_PRODUCT_SUCCESS = 'GET_SINGLE_PRODUCT_SUCCESS';
const GET_SINGLE_PRODUCT_END = 'GET_SINGLE_PRODUCT_END';
const GET_SINGLE_BRAND_SUCCESS = 'GET_SINGLE_BRAND_SUCCESS';
const CLEAR_ALERT = 'CLEAR_ALERT';
const SET_ALERT = 'SET_ALERT';
const DELETE_PRODUCT_BEGIN = 'DELETE_PRODUCT_BEGIN';
const DELETE_PRODUCT_SUCCESS = 'DELETE_PRODUCT_SUCCESS';
const DELETE_PRODUCT_FAILED = 'DELETE_PRODUCT_FAILED';
const SET_EDIT = 'SET_EDIT';
const UPDATE_PRODUCT_BEGIN = 'UPDATE_PRODUCT_BEGIN';
const UPDATE_PRODUCT_SUCCESS = 'UPDATE_PRODUCT_SUCCESS';
const UPDATE_PRODUCT_FAILED = 'UPDATE_PRODUCT_FAILED';
const CREATE_CONSUMER_BEGIN = 'CREATE_CONSUMER_BEGIN';
const CREATE_CONSUMER_SUCCESS = 'CREATE_CONSUMER_SUCCESS';
const CREATE_CONSUMER_FAILED = 'CREATE_CONSUMER_FAILED';
const GET_CONSUMERS_BEGIN = 'GET_CONSUMERS_BEGIN';
const GET_CONSUMERS_SUCCESS = 'GET_CONSUMERS_SUCCESS';
const GET_CONSUMERS_FAILED = 'GET_CONSUMERS_FAILED';
const SEND_MESSAGE_BEGIN = 'SEND_MESSAGE_BEGIN';
const SEND_MESSAGE_SUCCESS = 'GET_CONSUMERS_SUCCESS';
const SEND_MESSAGE_FAILED = 'GET_CONSUMERS_FAILED';
const TOGGLE_LOADING = 'TOGGLE_LOADING';
const CLAIM_COUPON_BEGIN = 'CLAIM_COUPON_BEGIN';
const CLAIM_COUPON_SUCCESS = 'CLAIM_COUPON_SUCCESS';
const CLAIM_COUPON_FAILED = 'CLAIM_COUPON_FAILED';
const GET_ALL_BRANDS_SUCCESS = 'GET_ALL_BRANDS_SUCCESS';
const GET_ALL_ADVERTS_SUCCESS = 'GET_ALL_ADVERTS_SUCCESS';
const CREATE_ADVERT_SUCCESS = 'CREATE_ADVERT_SUCCESS';

export {
  LOGIN_START,
  LOGIN_SUCCESS,
  LOGIN_FAILED,
  GET_LINKS_START,
  GET_LINKS_SUCCESS,
  GET_LINKS_FAILED,
  CREATE_LINKS_START,
  CREATE_LINKS_SUCCESS,
  CREATE_LINKS_FAILED,
  GET_BRANDS_START,
  GET_BRANDS_SUCCESS,
  GET_BRANDS_FAILED,
  // CREATE_BRANDS_START,
  // CREATE_BRANDS_SUCCESS,
  // CREATE_BRANDS_FAILED,
  GET_SINGLE_PRODUCT_BEGIN,
  GET_SINGLE_PRODUCT_SUCCESS,
  GET_SINGLE_PRODUCT_END,
  GET_SINGLE_BRAND_SUCCESS,
  CLEAR_ALERT,
  SET_ALERT,
  DELETE_PRODUCT_BEGIN,
  DELETE_PRODUCT_SUCCESS,
  DELETE_PRODUCT_FAILED,
  SET_EDIT,
  UPDATE_PRODUCT_BEGIN,
  UPDATE_PRODUCT_SUCCESS,
  UPDATE_PRODUCT_FAILED,
  CREATE_CONSUMER_BEGIN,
  CREATE_CONSUMER_SUCCESS,
  CREATE_CONSUMER_FAILED,
  GET_CONSUMERS_BEGIN,
  GET_CONSUMERS_SUCCESS,
  GET_CONSUMERS_FAILED,
  SEND_MESSAGE_BEGIN,
  SEND_MESSAGE_SUCCESS,
  SEND_MESSAGE_FAILED,
  TOGGLE_LOADING,
  CLAIM_COUPON_BEGIN,
  CLAIM_COUPON_SUCCESS,
  CLAIM_COUPON_FAILED,
  GET_ALL_BRANDS_SUCCESS,
  GET_ALL_ADVERTS_SUCCESS,
  CREATE_ADVERT_SUCCESS,
};
